#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

rm -rfv mesra*-t* &> /dev/null
rm inp_* &> /dev/null
rm mesra_general_info &> /dev/null
rm -rfv mesra-* &> /dev/null
rm detachment*.fchk &> /dev/null
rm attachment*.fchk &> /dev/null
rm da*.eig &> /dev/null
rm mesra.err &> /dev/null
rm DeltaU*.fchk DeltaR*.fchk &> /dev/null
rm *.orth &> /dev/null
rm *gammaZ*.fchk &> /dev/null
rm adiabZ.log &> /dev/null
rm acVec_Z.log &> /dev/null
rm header_fchk &> /dev/null
rm qmNI*.log &> /dev/null
rm *.ac &> /dev/null
