#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Acquires information to prepare a mesra_general_info file.
# Also checks if the required files are present in the working directory.

soft=`echo $2`

if [ $soft = 'g16' ] ; then

name=`basename $3 .fchk`
ntr=`ns_reader $3`

elif [ $soft = 'g03' -o $soft = 'g09' ] ; then
 
name=`basename $3 .fchk`
ntr=`echo $4`


elif [ $soft = 'qp' ] ; then

 :

else

 echo 'Only g03, g09, g16 and qp softwares are supported'
 echo 'Exit'
 exit

fi

if [ $soft = 'g03' -o $soft = 'g09' -o $soft = 'g16' ] ; then

 ls $3 &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo "Where is the $3 file?"
  echo 'Exit'
  exit
 fi

 ls overlap &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo 'Where is the overlap file?'
  echo 'Exit'
  exit
 fi

 ls density &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo 'Where is the density file?'
  echo 'Exit'
  exit
 fi

 if [ $ntr -eq 0 -o $ntr -eq 1 ] ; then
  echo "More than one transition should be computed when using Gaussian"
  echo 'Exit'
  exit
 fi

fi

echo $soft > mesra_general_info
echo "$name.fchk" >> mesra_general_info
echo overlap >> mesra_general_info
echo density >> mesra_general_info
echo $ntr >> mesra_general_info

echo 'General information collected into mesra_general_info'
