#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Checks that a prep process has been done before.

ls mesra_general_info &> /dev/null

if [ $? -eq 0 ] ; then
:
else
 echo "Error: No general information available, start by using the prep keyword" >> mesra.err
 echo "Exit" >> mesra.err
 exit
fi

# Collects information from the mesra_general_info

# Which software has been used?

soft=`head -1 mesra_general_info`

# If the Gaussian package has been used for the calculations, reads additional information.

if [ $soft = 'g03' -o $soft = 'g09' -o $soft = 'g16' ] ; then

# Reads the name of the fchk file.

namefchk=`head -2 mesra_general_info | tail -1`

# Reads the number of alpha and beta electrons in the fchk, to determine whether the
# calculation was restricted or unrestricted.

numalpha=`grep 'Number of alpha' $namefchk | awk '{print $6}'`
numbeta=`grep 'Number of beta' $namefchk | awk '{print $6}'`
diffnumalphabeta=`echo $numalpha - $numbeta | bc -l`

# Prepares an fchk header for future mesra outputs.

if [ $1 = 'orbsXY' -o $1 = 'pNTOs' -o $1 = 'CTOs' -o $1 = 'aNTOs' ] ; then
 nline_AlphaOrb=`grep -n 'Alpha Orbital' $namefchk | awk '{print $1}' | sed "s/:/ /" | awk '{print $1}'`
 nline_AlphaOrb_minus_one=`echo $nline_AlphaOrb -1 | bc -l`
 head -n $nline_AlphaOrb_minus_one $namefchk > header_fchk
fi

if [ $1 = 'dau' -o $1 = 'daz' -o $1 = 'dar' -o $1 = 'daXY' -o $1 = 'rlxypa' -o $1 = 'rlxy_PA' ] ; then
 nline_SCF=`grep -n 'Total SCF Density' $namefchk | awk '{print $1}' | sed "s/:/ /" | awk '{print $1}'`
 nline_SCF_minus_one=`echo $nline_SCF -1 | bc -l`
 head -n $nline_SCF_minus_one $namefchk > header_fchk
fi

name=`basename $namefchk .fchk`

# Reads the total number of transitions, and the number of the transition of interest.

ntr=`tail -1 mesra_general_info`
t=`echo $2`

# Calls the default_xPA routine, which returns 50 if there is nothing suitable in the arguments.

default_xPA $3 > defaultxPAfile

PA=`cat defaultxPAfile`

# If decimal number has been provided, returns an error.
# It also returns an error is no population analysis has been required together with an alphaddagger calculation.

fgrep "." defaultxPAfile &> /dev/null

if [ $? -eq 0 ] ; then
 echo Error: PA exponent should be between 0 and 100 >> mesra.err.temp ;
 echo Exit >> mesra.err.temp 
else
 if [ $PA = 'nopa' ] ; then
  PA_status=`echo noPA` ;
  xPA=`echo `
  if [ $1 = 'alphaddagger' ] ; then
   echo Error: nopa not permitted with the alphaddagger jobtype >> mesra.err.temp
   echo Exit >> mesra.err.temp
  fi
 elif [ $PA = 'scanpa' ] ; then
  PA_status=`echo scan` ;
  xPA=`echo `
 else
  PA_status=`echo PA` ;
  xPA=`cat defaultxPAfile | bc -l` ;
  if [ $xPA -lt 0 -o $xPA -gt 100 ] ; then
   echo Error: PA exponent should be between 0 and 100 >> mesra.err.temp ;
   echo Exit >> mesra.err.temp 
  fi
 fi
fi

rm defaultxPAfile

# Checks that the information provided by the user is compatible with the requested use of mesra.

requisites $namefchk $ntr $t &> mesra.err

# If an alphaddagger calculation has been requested, uses specific 'requisites' routines.

if [ $1 = 'alphaddagger' ] ; then

 ls mesra-t$t &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  mkdir mesra-t$t
 fi

 cd mesra-t$t

 if [ $diffnumalphabeta -eq 0 ] ; then
  requisites_alphaddagger &> mesra.err.temp_alphaddagger
 else
  requisites_alphaddagger_unrestricted &> mesra.err.temp_alphaddagger
 fi

# Manages the error files.

 ls mesra.err.temp &> /dev/null

 if [ $? -eq 0 ] ; then
  cat mesra.err.temp >> ../mesra.err ;
  rm mesra.err.temp ;
 else
  :
 fi

 ls ../mesra.err.temp &> /dev/null

 if [ $? -eq 0 ] ; then
  cat ../mesra.err.temp >> ../mesra.err ;
  rm ../mesra.err.temp ;
 else
  :
 fi

 ls mesra.err.temp_alphaddagger &> /dev/null

 if [ $? -eq 0 ] ; then
  cat mesra.err.temp_alphaddagger >> ../mesra.err ;
  rm mesra.err.temp_alphaddagger ;
 else
  :
 fi

 grep 'Error' ../mesra.err &> /dev/null

 if [ $? -eq 0 ] ; then
  exit
 else
  :
 fi

else
 :
fi

# Eventually checks errors if an error file remains.

ls mesra.err.temp &> /dev/null

if [ $? -eq 0 ] ; then
 cat mesra.err.temp >> mesra.err ;
 rm mesra.err.temp ;
else
 :
fi

grep 'Exit' mesra.err &> /dev/null

if [ $? -eq 0 ] ; then
 cat mesra.err
 exit
else
 :
fi

# If the software used is the quantum package, continues.

elif [ $soft = 'qp' ] ; then
 :
fi

# Checks if the sub-working directory is present. If not, creates it.
# If alphaddagger computation has been requested, we are already in the sub-working directory.


if [ $1 = 'alphaddagger' ] ; then
 :
else
 ls mesra-t$t &> /dev/null
 
 if [ $? -eq 0 ] ; then
  :
 else
  mkdir mesra-t$t
 fi
fi

# Starts preparing the input for mesra.
# Specific precautions are taken for alphaddagger computations since we are 
# already in the sub-working directory.

echo "$1" > inp_mesra-$1-$name-t$t 

if [ $1 = 'alphaddagger' ] ; then
 cat ../mesra_general_info >> inp_mesra-$1-$name-t$t
else
 cat mesra_general_info >> inp_mesra-$1-$name-t$t 
fi

echo $t >> inp_mesra-$1-$name-t$t 
echo $PA_status >> inp_mesra-$1-$name-t$t
echo $xPA >> inp_mesra-$1-$name-t$t

if [ $1 = 'alphaddagger' ] ; then
 cat alphaddagger_dat >> inp_mesra-$1-$name-t$t
 cp ../overlap .
fi

# Launches the mesra software.

main_mesra inp_mesra-$1-$name-t$t

# Removes useless or doubled files.

rm alphaddagger_dat &> /dev/null
rm inp_mesra-$1-$name-t$t &> /dev/null

if [ $1 = 'alphaddagger' ] ; then
 rm overlap &> /dev/null
 cd ..
fi
