#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Checks that the keywords and required files are ok.

touch mesra.err

ls $1 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
echo "Error: Where is the $1 file?" >> mesra.err
echo "Exit" >> mesra.err
fi


ls $2 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
echo "Error: Where is the $2 file?" >> mesra.err
echo "Exit" >> mesra.err
fi

if [ $4 = 'p' ] ; then
:
elif [ $4 = 'm' ] ; then
:
else
echo "Error: only 'p' and 'm' are permitted for argument 5" >> mesra.err
echo "Exit" >> mesra.err
fi

if [ $5 = 'p' ] ; then
:
elif [ $5 = 'm' ] ; then
:
else
echo "Error: only 'p' and 'm' are permitted for argument 6" >> mesra.err
echo "Exit" >> mesra.err
fi

grep 'Exit' mesra.err &> /dev/null

if [ $? -eq 0 ] ; then
exit
else
:
fi

# Prepares the input.

echo "cubeop" > inp_cubeop
echo "$1" >> inp_cubeop
echo "$2" >> inp_cubeop
echo "$3" >> inp_cubeop
echo "$4" >> inp_cubeop
echo "$5" >> inp_cubeop

# Launches the mesra computation.

main_mesra inp_cubeop

rm inp_cubeop &> /dev/null

