#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

touch mesra.err

# Checks that the required files are present, and launches directly the numerical integration using mesra.

ls $2 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
 echo "Error: Where is the $2 file?" >> mesra.err
 echo "Exit" >> mesra.err
fi

ls $3 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
 echo "Error: Where is the $3 file?" >> mesra.err
 echo "Exit" >> mesra.err
fi

grep 'Exit' mesra.err &> /dev/null

if [ $? -eq 0 ] ; then
exit
else
:
fi

echo "$1" > inp_mesra-$1 
echo "$2" >> inp_mesra-$1
echo "$3" >> inp_mesra-$1

main_mesra inp_mesra-$1 

rm inp_mesra-$1 &> /dev/null
rm mesra-Job-qm_NI.log &> /dev/null

