#!/bin/bash

touch mesra.err

# Checks that the required files are present, and launches directly the numerical integration using mesra.

ls $2 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
 echo "Error: Where is the $2 file?" >> mesra.err
 echo "Exit" >> mesra.err
fi

ls $3 &> /dev/null

if [ $? -eq 0 ] ; then
:
else
 echo "Error: Where is the $3 file?" >> mesra.err
 echo "Exit" >> mesra.err
fi

grep 'Exit' mesra.err &> /dev/null

if [ $? -eq 0 ] ; then
exit
else
:
fi

echo "$1" > inp_mesra-$1 
echo "$2" >> inp_mesra-$1
echo "$3" >> inp_mesra-$1

main_mesra inp_mesra-$1 

rm inp_mesra-$1 &> /dev/null
rm mesra-Job-qm_NI.log &> /dev/null

