#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

nstates=`grep -i 'nstates' $1`
nstates_nws="$(echo -e "${nstates}" | tr -d '[:space:]')"

nsvar=`echo -e $nstates_nws | tr [:upper:] [:lower:] | awk '{split($0,a,"nstates=") ; print a[2]}'`

for (( i=0; i<${#nsvar}; i++ )); do
  echo "${nsvar:$i:1}" >> ns_letter_by_letter
done

for f in $(cat ns_letter_by_letter)
do
 if [[ $f == "," ]];then
  rm ns_letter_by_letter &> /dev/null
 break 
 elif [[ $f == " " ]];then
  rm ns_letter_by_letter &> /dev/null
  break
 elif [[ $f == ")" ]];then
  rm ns_letter_by_letter &> /dev/null
  break
 else 
  echo $f >> number_of_transitions
  rm ns_letter_by_letter &> /dev/null
 fi
done

noftr=`cat number_of_transitions | wc -l`

for (( i=1 ; i<$noftr+1 ; i++ )) ; do
 head -$i number_of_transitions | tail -1 > transtore-$i
done 

paste transtore-* > temp-transtore
cat temp-transtore | tr -d "[:space]" | tr -d "[:space:]"
 

rm number_of_transitions
rm *transtore*
