#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

here=`pwd`

# Goes into the mesra software src directory

loc=`which mesra`
dirloc=`dirname $loc`
cd $dirloc

mesra_home=`pwd`

cd ../src/

make clean &> /dev/null

# Copies the executable files

cp ./executables/* $mesra_home &> /dev/null

# Compiles

make
make clean

mv main_mesra $mesra_home

# Modifies the path and the bashrc file

ls ~/.bashrc &> /dev/null

if [ $? -eq 0 ] ; then

grep 'mesra' ~/.bashrc | grep 'PATH' &> /dev/null

if [ $? -eq 0 ] ; then
 PATH2=$mesra_home
 string=`echo \$PATH:`
 sed -i -e 's%\(.*\)\( # mesra home directory\)%PATH=$PATH:'$PATH2'\2%'  ~/.bashrc
 rm ~/.bashrc-e &> /dev/null
else
 echo PATH='$PATH':$mesra_home \# mesra home directory >> ~/.bashrc
fi 

. ~/.bashrc &> /dev/null
. ~/.profile &> /dev/null
. ~/.bash_profile &> /dev/null

else
 : 
fi

cd $here
