#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Checks that the general info, and appropriate files are available in the working directory.
# Also checks that the number of the target transition is lower than the total number of 
# transitions computed.

ls mesra_general_info &> /dev/null

if [ $? -eq 0 ] ; then
 :
else
 echo "Error: No general information available, start by using the prep keyword"
 echo 'Exit'
fi

if [ $3 -gt $2 ] ; then
 echo "Error: The transition number should be between 1 and $2"
 echo 'Exit'
fi

 ls $1 &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo "Error: Where is the $1 file?"
  echo 'Exit'
 fi

 ls overlap &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo 'Error: Where is the overlap file?'
  echo 'Exit'
 fi

 ls density &> /dev/null

 if [ $? -eq 0 ] ; then
  :
 else
  echo 'Error: Where is the density file?'
  echo 'Exit'
 fi

 if [ $2 -eq 0 -o $2 -eq 1 ] ; then
  echo "Error: More than one transition should be computed when using Gaussian"
  echo 'Exit'
 fi

