#!/bin/bash

# MESRA software
# Molecular Electronic Structure Reorganization: Analysis
# Copyright (C) 2019 Thibaud Etienne
# More information at mesrasoftware.wordpress.com
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to
# 
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

loc=`which mesra`
dirloc=`dirname $loc`
cd $dirloc
cd ../test
clean_mesra

cd restricted/tddft
mesra prep g16 pp3.fchk 6
mesra dau 1 
mesra daz 1 nopa
mesra dar 1 40
mesra dau 2
mesra orbsxy 2
mesra daxy 2
mesra rlxypa 1
clean_mesra

cd ../cis
mesra prep g16 push-pull.fchk 3
mesra dau 1
mesra dar 1
mesra orbsxy 2
mesra daxy 2
mesra alphaddagger 1
clean_mesra

cd ../../cubes
mesra qmni detachment.cube attachment.cube
clean_mesra

cd ../unrestricted/tddft/form
mesra prep g16 form.fchk 3
mesra dau 1
mesra orbsxy 1
mesra adiabz 1
mesra daxy 1 scanpa
clean_mesra

cd ../../cis/H2
mesra prep g16 H2.fchk 3
mesra dau 1
mesra orbsxy 1
clean_mesra


cd $here
